### ISSUE TITLE
Allow attribute names that mix `:` and `-`

### ISSUE THREAD

**Issue by gbj** [stoically/syn-rsx#33]
[My framework](https://github.com/gbj/leptos) is using `syn-rsx` for its `view` macro. I use `on:`, `class:`, and `prop:` as prefixes to add event listeners, toggle classes, and set properties.

A user pointed out to me that this causes issues for event names coming from custom elements, which are recommended to have a dash: e.g., `custom-event`. Currently `syn-rsx` can't parse `on:custom-event` as a valid node name; it either requires all colons or all dashes.

https://github.com/stoically/syn-rsx/blob/98cc893b725828cbf207246d752215496a7e1d76/src/parser.rs#L414-L433

I'm wondering if it would be possible to allow for a mix of colons and dashes in node names.

Editing to add: I'm happy to submit a PR if you'd like.

**Comment by stoically** [comment]
Hey, great work on leptos!

Allowing a combination of `:` and `-` sounds sensible. Two generic solutions come to mind:
- Add a node name parsing hook, similar to `ParserConfig::transform_block`, which would allow arbitrary parsing via callback hook.
- Add a new `NodeName::Punct(Punctuated<Ident, proc_macro2::Punct>)` variant and remove the `Colon` + `Dash` variants in favor of it. While this is flexible, we might still want to have an allowlist for which punctations should be allowed, since at least `=` would need special-casing

Both would be useful, I think.

If you want to work on either of the solutions, be my guest! Thumbs-up or short comment if you intend to do so would be helpful, otherwise I'll take a look if I get the chance.

There'd be also the possibility to add a new `NodeName::ColonDash((Ident, Colon, Punctuated<Ident, Dash>))` variant, but that seems a bit too specific. If you have totally different idea, I'd be interested in hearing that as well, of course!

**Comment by gbj** [comment]
I'll take a quick crack at it!
