### ISSUE TITLE
Allow NodeName to contain generics.

### ISSUE THREAD

**Issue by ChangeCaps** [stoically/syn-rsx#61]
I'm writing a UI crate called ori, and I'm using syn-rsx for this. A key feature of ori is the ability to implement custom elements, and i would love to be able to write something like.

```rust
view! {
<Select<&str> selected=value value="Item 1">
    "Item 1"
</Select<&str>>
}
```

But it seems that generics aren't supported in node names.

**Comment by vldm** [comment]
@ChangeCaps  Hi, why you need to explicitly type generics? Can you provide some examples of custom components, maybe with some explanation why generic cannot be infered from macro expansion.


I am not author of syn-rsx, just maintainer of [fork](https://github.com/stoically/syn-rsx/issues/58) and interested in all syntax extensions, but currently unsure if using <> inside tags is a good idea because it can confuse a user.
And a counterexample would be a good argument for it.

**Comment by vldm** [comment]
@ChangeCaps 
I implemented this in my fork, in https://github.com/rs-tml/rstml/pull/19

But it is done in separate field in open/close tags rather than inside `NodeName`.
I done it in this way for several reasons:
1. `NodeName` is also used inside attribute where generics  can't be used.
2. I want to reuse `syn::Generics` so it would be easier to integrate in macro infrastructure. (instead of implementing it as in https://docs.rs/syn/latest/syn/struct.PathSegment.html)
3. I want to reduce refactor cost to rstml users, so now if you don't need to support generics - you can just ignore this field.

**Comment by ChangeCaps** [comment]
> 

That's great, thank you.
